### ISSUE TITLE
num_resources different than 2

### ISSUE THREAD

**Issue by aecostas** [CAHLR/pyBKT#1]
In the test code, num_resources is harcoded to 2. When modifying it to, for instance, 20, it does not work

`fitting! each dot is a new EM initialization
.Traceback (most recent call last):
  File "test/hand_specified_model.py", line 56, in <module>
    (fitmodel, log_likelihoods) = EM_fit.EM_fit(fitmodel, data)
  File "/home/aestevez/devel/pyBKT/fit/EM_fit.py", line 38, in EM_fit
    model = M_step.run(model, result['all_trans_softcounts'], result['all_emission_softcounts'], result['all_initial_softcounts'])
  File "/home/aestevez/devel/pyBKT/fit/M_step.py", line 6, in run
    trans_softcounts[:, np.sum(trans_softcounts, axis=1) == 0] = 1
IndexError: boolean index did not match indexed array along dimension 1; dimension is 2 but corresponding boolean dimension is 20
`

Any hint to overcome this problem?

Thanks!

**Comment by zpardos** [comment]
Problem fixed in a recent pull request. An assert was using the wrong dimension in M_step, which was always 2 instead of the dimension that changes according to the number of resources.
