### ISSUE TITLE
Accessing global variable from child process on Windows is different from MacOS

### ISSUE THREAD

**Issue by ryf1123** [CAHLR/pyBKT#11]
When I was running `5.1_Basic.py` on Windows, it raised an error "NonType is not iterable". I found this is because of the `input` variable in `pyBKT/fit/EM_fit.py` as follows, (it is `None`)

```
def inner(x):
    for i in input:
        exec(i + " = input['" + i + "']", gs)
```

I think you might want to define a global `input` variable at the beginning of `pyBKT/fit/EM_fit.py` and modify it in `run function` as,

```
    input = {"As": As, "Bn": Bn, "initial_distn": initial_distn, 'allresources': allresources, \
             'starts': starts, 
             'lengths': lengths, \
             'num_resources': num_resources, 'num_subparts': num_subparts, \
             'alldata': alldata, 'normalizeLengths': normalizeLengths, 'alpha_out': alpha_out}
```

And then access it from the child process in the function `inner`. 

But the problem is I guess Windows is different. Considering the error, I think a newly created child process will not inherit the `input` variable: [link](https://docs.python.org/3.4/library/multiprocessing.html?highlight=repr)

```
spawn
The parent process starts a fresh python interpreter process. The child process will only inherit those resources necessary to run the process objects run() method. In particular, unnecessary file descriptors and handles from the parent process will not be inherited. Starting a process using this method is rather slow compared to using fork or forkserver.

Available on Unix and Windows. The default on Windows.

fork
The parent process uses os.fork() to fork the Python interpreter. The child process, when it begins, is effectively identical to the parent process. All resources of the parent are inherited by the child process. Note that safely forking a multithreaded process is problematic.

Available on Unix only. The default on Unix.
```   

Could you please give some hint to work it out or do you have any solution for this? Thank you for your feedback in advance!

**Comment by abadrinath947** [comment]
Sorry for the late reply! This is fixed now.
