### ISSUE TITLE
Updating the model

### ISSUE THREAD

**Issue by kim-anhvu** [CAHLR/pyBKT#16]
Hi,

Firstly, thank you for this library! 

I would like to know if there is a function or any way of updating the trained model with more recently obtained data? Or would I have to append the new data onto my existing dataset and retrain the whole model every time? Thank you in advance!

**Comment by abadrinath947** [comment]
Hi!

There wasn't a feature to do so under the new Model class abstraction, but I have just added a new partial_fit function that accomplishes this to the repository. This is similar to sklearn's partial_fit, and it can either be called after one instance of fit or one of more instances of partial_fit. An example is given in the documentation.

This isn't in the pip repository yet, so give it a try by git clone'ing, pip uninstall pyBKT, then `pip install .` from inside the pyBKT directory.
