### ISSUE TITLE
Make fail with boost >= 1.65 since numeric.hpp has been removed

### ISSUE THREAD

**Issue by Jinny-Wang** [CAHLR/pyBKT#2]
Since python/numeric.hpp has been removed from the latest version of boost, all the .cpp code including 
`#include <boost/python/numeric.hpp>` and namespace `numeric::array` will fail.  Any suggestion on fixing this?  I'm currently using boost 1.66.0 and I don't think modifying the source code line by line to replace `numeric` with `numpy` is a good idea.

**Comment by zpardos** [comment]
No fix as of right now. The default libboost on Ubuntu is still 1.58, which works. On OSX, brew uses >= 1.65 causing this to not work on Macs. Reverting to an older libboost is the only workaround right now. Do you know if the justification for its removal was a migration to numpy?

**Comment by anadaf** [comment]
Even reverting to the older version of libboost does not the problem at all. It produces another error messages.

**Comment by zpardos** [comment]
Hello, this has been resolved on Ubuntu by uninstalling your existing libboost and installing the following older compatible versions, depending on your version of Ubuntu.

14.04: apt install libboost1.55-all-dev

16.04: apt install libboost1.58-all-dev

18.04: apt install libboost1.62-all-dev

The Colab notbook example is now working using the 1.62 version: https://colab.research.google.com/drive/13iqM8mtYwtOKw3Ja4RS51ZTa4NnEQ26s?authuser=1
