### ISSUE TITLE
Issues with predicting the 't+1'th knowledge state

### ISSUE THREAD

**Issue by WoodyAhn** [CAHLR/pyBKT#22]
First of all, thanks for providing such a wonderful library.

One problem I am working on now is, predicting the 't+1'th knowledge state of a student.

'.predict' function returns the knowledge state of the specific row (let's say 't'th knowledge state)

but what I want is to predict the 't+1'th knowledge state of the student after he/she replies on 't'th question.

Could you give me a relevant solution to tackle this problem?

**Comment by zpardos** [comment]
The state predictions returned by predict() are what you are looking for. They are the result of the learning rate transition of the knowledge state value at t-1 (i.e., a prediction of the knowledge state at t). State predictions are only returned for the time slices for which there are data for the student. If you want a state prediction past the length of a student's sequence in the data, you can either manually calculate it (i.e., by calculating the posterior and then applying the learning rate) or you can add a synthetic row to the raw data with a time slice ahead of the last response and with the same skill and userid. The response won't be used, so it can take on any value [-1, 0, 1].

**Comment by WoodyAhn** [comment]
Thank you for the detailed response! 
I will add a synthetic row to the raw data
