### ISSUE TITLE
Why the prediction results vary greatly each time? (knowledge_concept, state_predictions etc.)

### ISSUE THREAD

**Issue by bukeplato** [CAHLR/pyBKT#27]
Happy new year! And thank you for this great project.

I'm learning to use this library through your tutorial examples. But it confuse me that the prediction results vary each time(picture1&2 0.58931→0.21604, 0.19756→0.78351), when I try your examples with project provided Cognitive Tutor dataset. 

When I try my own data(including 4 knowledge concepts, and 8 records per knowledge concepts, only one user), prediction results vary more greatly.(picture 3&4)

It confuse me. With unchanged dataset, why the results vary so greatly? rmse, auc and other metrics also different each time. 

(picture 1&2)
![pycharm64_20220103101128_1035_2346x532](https://user-images.githubusercontent.com/10812644/147896642-a486378f-e6c4-4396-9e2b-1b3ee564fe4c.png)
![pycharm64_20220103104559_1041_2153x446](https://user-images.githubusercontent.com/10812644/147896568-402b938d-c0fd-4fd3-9eff-11d077033f6d.png)
(picture 3&4)
![pycharm64_20220103101611_1038_864x431](https://user-images.githubusercontent.com/10812644/147896488-b2d121f5-1751-4ac4-86fd-de87afb0aa4a.png)
![pycharm64_20220103101621_1039_927x443](https://user-images.githubusercontent.com/10812644/147896495-a62214b8-d457-4be5-9f4f-d939f6b7a334.png)

**Comment by bukeplato** [comment]
I guess the issue may caused by model initialization... Model generate random initialization states each time.
Could I set a reproducible seed  to repeat the experiment with exactly the same initialization states? Or set initialization states manually?

**Comment by fredwang25** [comment]
Hi! You can set the random seed of your model when creating the model instance like so:

`model = Model(seed = 42)`
