### ISSUE TITLE
Does pyBKT supports additional features beyond 'correct' and 'skill_id' ?

### ISSUE THREAD

**Issue by bernardoleite** [CAHLR/pyBKT#28]
Hi there,

First of all, I congratulate you on this amazing project! 
There are some studies exploring the encoding of multiple features which help to improve the prediction of KT models (e.g., `attempt number`, `time`, `tutor intervention`, etc...), beyond `correctness `and `skill`.

Would it be possible to confirm if pyBKT supports the encoding of additional features besides `correctness `and `skill`? 
If so, would it be possible to illustrate how to proceed with this encoding process?

Thanks in advance.

**Comment by abadrinath947** [comment]
Please look at the tutorial for how to enable multiple guess, slip, learn and forget rates through the model extensions we provide (i.e. multigs, multilearn, etc.). For all unique values of the column or feature specified, it will learn a separate rate (whether it's learn, slip, etc.).
