### ISSUE TITLE
Skill iterable?

### ISSUE THREAD

**Issue by veronaxteo** [CAHLR/pyBKT#30]
Trying to set values/parameters of all skills; is there an easy way to set for all (instead of current dictionary format), or get a list of skills from model object after loading in data?

**Comment by abadrinath947** [comment]
No - there isn't an easier way than writing a loop unfortunately. If you have a particular dictionary of parameters you would like to set, you may pass that in for each skill using a dictionary comprehension or `zip`, etc. For a list of skills from the model object, you may use `model.params().reset_index()['skill'].unique()` or `model.coef_.keys()`.
