### ISSUE TITLE
AttributeError: 'Roster' object has no attribute 'students'

### ISSUE THREAD

**Issue by SuJiaKuan** [CAHLR/pyBKT#31]
My pyBKT version is 1.4, and the error occurs when running following code lines:

```python
from pyBKT.models import Model
from pyBKT.models import Roster

model = Model()
model.fit(data_path = 'ct.csv')

roster = Roster(students=['Jeff', 'Bob'], skills='Calculate unit rate', model=model)
print(roster)
```

The error message:
```bash
Traceback (most recent call last):
  File "bkt_2.py", line 75, in <module>
    main()
  File "bkt_2.py", line 15, in main
    print(roster)
  File "/home/feabries/anaconda3/envs/cognitive/lib/python3.8/site-packages/pyBKT/models/Roster.py", line 381, in __repr__
    return 'Roster(%s, %s, %s, %s, %s)' % (repr(len(self.students)), repr(self.skills),
AttributeError: 'Roster' object has no attribute 'students'
```

It seems that the `__repr__()` in [source-py/pyBKT/models/Roster.py](https://github.com/CAHLR/pyBKT/blob/master/source-py/pyBKT/models/Roster.py#L381) method uses non-existing attributes `self.students` when I try to print the roster object?

**Comment by abadrinath947** [comment]
Apologies for the extremely late reply. This bug has been resolved in the repository, so please run `pip install .`.

We will release a patch version soon.
