### ISSUE TITLE
Inconsistent state_predictions

### ISSUE THREAD

**Issue by themrzmaster** [CAHLR/pyBKT#36]
Hi  !

It looks like the state_predictions is not right.
![image](https://user-images.githubusercontent.com/852747/219464849-c21fce11-0634-48b9-887a-9ada64d1edb3.png)
![image](https://user-images.githubusercontent.com/852747/219464874-70ebf1fb-961d-4162-a42a-dc4590f153f1.png)

When a student gets all right the state prediction is low.
Also, when he dooes something wrong, the state prediction increases.
I am using the lastest git version

**Comment by zpardos** [comment]
Hello,

Please share a notebook file for full replication so we can look into it.

**Comment by themrzmaster** [comment]
thanks, can I email it to you?

**Comment by abadrinath947** [comment]
Looking into this - will get back to you on what the issue(s) might be!

**Comment by abadrinath947** [comment]
As responded over email, this seems to be an issue with the data that leads to degenerate model parameters as a result of the fitting procedure. I don't believe this is a bug with pyBKT.
