### ISSUE TITLE
Latest pyBKT not built

### ISSUE THREAD

**Issue by ahaim5357** [CAHLR/pyBKT#37]
Currently, the last built release of pyBKT on PyPI is 1.4 from 11/19/2021. Since then, there has been an accepted PR #35 fixing an issue with `scikit-learn` as a dependency.  However, as this version has not been built, the issue still persists even though it has been resolved. The current workaround is just to build pyBKT manually or install `scikit-learn` separately.

**Comment by MattoCl** [comment]
👍  i want this too!

**Comment by abadrinath947** [comment]
Apologies for the long delay - we have now built `pyBKT` version 1.4.1 and it has been released on `pip`!
