### ISSUE TITLE
Seeded models using pyBKT (C++) are not deterministic

### ISSUE THREAD

**Issue by ahaim5357** [CAHLR/pyBKT#39]
## Issue

When attempting to run the examples provided by [pyBKT-examples](https://github.com/CAHLR/pyBKT-examples) which contain seeded values for the model, the results after multiple runs are not deterministic. Here are some of the values obtained (using `BasicForgets.py` as our example):

```
---Trial 1---
Standard BKT: 0.7592625187866002
BKT+Forgets: 0.8247110306117472
---Trial 2---
Standard BKT: 0.7597630670796617
BKT+Forgets: 0.8246438122020618
---Trial 3---
Standard BKT: 0.7594897026114035
BKT+Forgets: 0.8244289337594783
---Trial 4---
Standard BKT: 0.7592787479735561
BKT+Forgets: 0.8249778157710541
---Trial 5---
Standard BKT: 0.7594278427714183
BKT+Forgets: 0.8250750048641349
````

While the significance of reporting used makes the randomness irrelevant, deterministic behavior should still remain consistent across implementations.

This likely stems from two issues based on tests:

1. Python randomness is not seeded between model runs
2. C++ thread execution does not produce deterministic behavior (Unsure)

## Solution Issue 1

It seems as though the Python randomness is managed by the regular random and numpy's random. As such, when we seed the two values, we get the following:

```
---Trial 1---
Standard BKT: 0.7592808292007402
BKT+Forgets: 0.8243054787023159
---Trial 2---
Standard BKT: 0.7592808362843335
BKT+Forgets: 0.8243054675709549
---Trial 3---
Standard BKT: 0.7592808359470197
BKT+Forgets: 0.8243054810635136
---Trial 4---
Standard BKT: 0.7592808307186532
BKT+Forgets: 0.824305476678432
---Trial 5---
Standard BKT: 0.7592808302126821
BKT+Forgets: 0.8243054780276879
```

The results are a lot more deterministic to around 6 or 7 digits compared to the previous 2 or 3.

## Solution Issue 2?

This issue I have been looking into for a while now, but I'm unsure whether this is truly the case. My general inclination is that the single threaded critical section within the multithreaded run section in E_step is producing a different access order of the data depending on the completion speed of each thread. As such it would probably make sense to insert the data into the map using the thread number. However, I wouldn't be surprised if the issue was from a different location.

**Comment by abadrinath947** [comment]
Thank you for catching this issue! My belief is that the first solution is likely correct and that the remaining differences can perhaps be attributed to some floating point error. I can certainly investigate the possibility you mentioned though.

If possible, would you be able to create a PR so we can push this code change to the repository?

Anirudhan

**Comment by ahaim5357** [comment]
> Thank you for catching this issue! My belief is that the first solution is likely correct and that the remaining differences can perhaps be attributed to some floating point error. I can certainly investigate the possibility you mentioned though.

I do remember recalling that parallel blocked algorithms could be non-deterministic there with floating point operations. However, thinking about this more, a float would normally only have about 7 digits of precision. With the mixed bag of double to float conversions from Python to C++, I would say its reasonable to mark as insignificant because the reporting significance is between 2 to 4 digits according to your examples.

> If possible, would you be able to create a PR so we can push this code change to the repository?

Sure., it only requires a few changes from what I remember.
