### ISSUE TITLE
Question about model parameters ['multilearn', 'multiprior', 'multipair', 'multigs']

### ISSUE THREAD

**Issue by mathisfo** [CAHLR/pyBKT#40]
Hi,

Im writing a master's thesis on knowledge tracing, and your package is superior to any of the other alternatives I have looked into. 

I just completed a one-month (n=87) trial phase where students have done Java exercises. Multiple guesses are allowed on one question. 50% of the sample size are first-year students, the other second year. Thus, the prior knowledge L0 is different.

**Q1:**
How would I setup up the model to accommodate multiple retries and adjust prior level? Is `multiprior` and `multigs` the ones I'm looking for?

**Q2**

```python
def main():
    # Initialize the model with an optional seed
    model = Model(seed=42, num_fits=1)

    df = pd.read_csv("data/coding.csv")


    model.fit(data=df, skills="Strings")

    preds_df = model.predict(data=df)

    preds_df[preds_df["skill_name"] == "Strings"][
        ["user_id", "correct", "correct_predictions", "state_predictions"]
    ].to_csv("coding.csv", index=False)


if __name__ == "__main__":
    main()
```

The prediction on the skill "Strings" have state_predictions that are very low if the students suddenly answer incorrectly. One incorrect answer impacts the state prediction severely, and despite correct answers afterwards, the prediction does not rise significantly. (Observer studentID norway22117) in the screenshot below. (Note: that despite correct being 1, the student may have had several attempts before it was correct. This is stored as the `attempt_count` in my dataset.

<img width="394" alt="Screenshot 2023-04-25 at 12 52 09" src="https://user-images.githubusercontent.com/43377191/234255363-a0e57554-49d1-4e9a-bca9-15413cd1aa93.png">

**Q3**

How would I find the guess and slip rates for each student in the dataset I have collected? Does the `model.params()` display slip and guess predictions for just the entire student class (the whole dataset)?

Thanks in advance!

**Comment by mathisfo** [comment]
After some different model setup. Setting multiprior True, make the state_predictions not drop as hard anymore.

**Comment by abadrinath947** [comment]
Thank you for the kind words and for using our package! I've answered your questions below:

Q1: For multiple retries, BKT typically uses accepts the first answer attempted and doesn't consider retries. If you would like to consider retries as if they were first responses, you would make multiple rows corresponding to each retry. Each of them will be treated as fresh responses.

To have multiple priors, you are looking for `multiprior`, though it is somewhat limited and typically does not perform as well as multiplexing/individualizing the guess/slip rates using `multigs`.

Q2: The drop in state predictions could be due to a very high forget rate being fitted. You may true to disable forgets, setting `forgets = False`.  It would be helpful to see your `model.params()` to see what's going on.

Q3: You are correct - `model.params()` will contain that information. The guess and slip rates will be the same for all students. If you want to fit one for each student, you can use `multigs = 'User_id'`, which learns a guess and slip rate for each user.

**Comment by mathisfo** [comment]
Thank you for a very detailed answer!

> Q1: For multiple retries, BKT typically uses accepts the first answer attempted and doesn't consider retries. If you would like to consider retries as if they were first responses, you would make multiple rows corresponding to each retry. Each of them will be treated as fresh responses.

This is a great idea. I've made some tests with promising results.

> To have multiple priors, you are looking for `multiprior`, though it is somewhat limited and typically does not perform as well as multiplexing/individualizing the guess/slip rates using `multigs`.

I did see that multiprior did not perform as well as I initially thought.

> Q2: The drop in state predictions could be due to a very high forget rate being fitted. You may true to disable forgets, setting `forgets = False`. It would be helpful to see your `model.params()` to see what's going on.

After separating the attempts into their own rows, the drop is not as significant anymore.

> Q3: You are correct - `model.params()` will contain that information. The guess and slip rates will be the same for all students. If you want to fit one for each student, you can use `multigs = 'User_id'`, which learns a guess and slip rate for each user.

I've used multigs='User_id'  and forgets=False on the dataset which considers retries as fresh responses as per your suggestion. Seems like the prior knowledge is set to 0 for all students. The `state_prediciton` increases when the user answers incorrectly. Observe how the student answers incorrectly here: 

<img width="413" alt="image" src="https://user-images.githubusercontent.com/43377191/235649759-42d4e889-34b6-4bc8-a119-a9e004f3ab17.png">

When using multiprior tough, I get this RuntimeWarning: 
<img width="998" alt="image" src="https://user-images.githubusercontent.com/43377191/235650638-0efe1a67-233a-49ee-a31b-e6a2f0aba94e.png">

The `model.params()` for Forgets=True, multigs='User_id' is and `norway22138`student: 
"('Strings', 'prior', 'default')": 0.0,
 "('Strings', 'learns', 'default')": 0.250290969,

"('Strings', 'guesses', 'norway22108')": 0.0,
"('Strings', 'slips', 'norway22108')": 1.0,


For the second-year students I have their grades for their first year performance. Could I create custom priors for each of these students using a numeric value for their grade?


So far the most promising results are just a basic model with Forgets=False

**Comment by abadrinath947** [comment]
A slip value of 1.0 is an indication of a degenerate parameter. Effectively, it says that given a student is mastered, they have a probability of 100% of getting the question wrong. In theory, you should have your trained slip and guess values be less than 0.5. Parameter fixing or initialization can help you here (take a look at the README for how to do this!).

You could create a custom prior and fix it, but I am not sure if you'd be able to create and fix a different prior for each student in `pyBKT`. I suspect parameter degeneracy is a big part of the reason you're having issues, and parameter fixing/initialization is certainly the way to go with that using EM.

**Comment by abadrinath947** [comment]
Closing the issue due to lack of activity. Feel free to reopen if you have any questions!
