### ISSUE TITLE
multilearn and multiprior cannot be fitted together

### ISSUE THREAD

**Issue by capriceZ** [CAHLR/pyBKT#46]
Hello again,

Because multiprior is implemented as different learning rates rather than true different priors, we cannot set multilearn=True and multiprior=True at the same time, right? I already tested it with data and knew we cannot do this. Just wanted to confirm my understanding. 

Thank you!

**Comment by abadrinath947** [comment]
I believe this is the case, yes. At the very least, I do not think `pyBKT` supports this.
