### ISSUE TITLE
predict_onestep_states.cpp

### ISSUE THREAD

**Issue by cloudspurs** [CAHLR/pyBKT#6]
line 138, 
    forward_messages_temp[i+j] = extract<double>(forward_messages[i][j]);
I think so
   forward_messages_temp[i*bigT+j] = extract<double>(forward_messages[i][j]);

**Comment by zpardos** [comment]
Resolved by https://github.com/CAHLR/pyBKT/commit/46d468ffd47b2dca35b784b475d7104ee5b2038b
