### ISSUE TITLE
Questions on E_step.cpp and predict_onestep_states.cpp

### ISSUE THREAD

**Issue by yuting921** [CAHLR/pyBKT#8]
Hi all! 

I was running a standard BKT model using the pyBKT and got an error when doing prediction using predict_onestep.py: some states prediction probabilities return nan. I looked into the code and found out:
1. In predict_onestep_states.cpp, line 138, when assigning a double array:
` forward_messages_temp[i+j] = extract<double>(forward_messages[i][j]);`
maybe should be:
` forward_messages_temp[i*bigT+j] = extract<double>(forward_messages[i][j]);`
A same issue can be found [here](https://github.com/CAHLR/pyBKT/issues/6).
2. In E_step.cpp, function _run()_ return a dict value _result_. I suppose result['alpha'] should be a list of two list, one list is the state probability for state `unknown` and another one is the state probability for state `learned`. And `result['alpha'][0][i] + result['alpha'][1][i] == 0` should be true. But when I print the value out it seems like it is not. Any ideas on this?

Thanks!

**Comment by zpardos** [comment]
Hello yuting921,

I've added you to the project as a contributor. If you like, please issue a pull request that reflect these changes so that your modifications can be properly reviewed and credited.
